import { IDatesPeriod } from './dates';

export enum IPdfWidgetCategory {
  TPPS = 'TPPS',
  JWKMS = 'JWKMS',
  DIRECTORY = 'DIRECTORY',
  SECURITY = 'SECURITY',
  ACCOUNTS = 'ACCOUNTS',
  PAYMENTS = 'PAYMENTS',
  CONFIRMATION_OF_FUNDS = 'CONFIRMATION_OF_FUNDS',
  EVENTS_NOTIF = 'EVENTS_NOTIF',
  GSU = 'GSU',
  SETTINGS = 'SETTINGS'
}

export enum IPdfWidgetType {
  // TPPs
  DOUGHNUT_TPPS_ORIGIN = 'DOUGHNUT_TPPS_ORIGIN',
  BAR_TPPS_ROLES = 'BAR_TPPS_ROLES',
  LINE_TPPS_REGISTRATION = 'LINE_TPPS_REGISTRATION',
  TABLE_TPPS_ENTRIES = 'TABLE_TPPS_ENTRIES',
  TABLE_TPPS_API_USAGE = 'TABLE_TPPS_API_USAGE',
  // JWKMS
  TABLE_JWKMS_USAGE = 'TABLE_JWKMS_USAGE',
  COUNTER_JWKMS_VALIDATION = 'COUNTER_JWKMS_VALIDATION',
  COUNTER_JWKMS_GENERATED = 'COUNTER_JWKMS_GENERATED',
  DOUGHNUT_JWKMS_NUMBER_OF_KEYS = 'DOUGHNUT_JWKMS_NUMBER_OF_KEYS',
  // Directory
  COUNTER_DIRECTORY_ORGANISATION_REGISTERED = 'COUNTER_DIRECTORY_ORGANISATION_REGISTERED',
  COUNTER_DIRECTORY_SOFTWARE_STATEMENTS_REGISTERED = 'COUNTER_DIRECTORY_SOFTWARE_STATEMENTS_REGISTERED',
  COUNTER_DIRECTORY_SSA_GENERATED = 'COUNTER_DIRECTORY_SSA_GENERATED',
  COUNTER_DIRECTORY_DOWLOADING_KEYS = 'COUNTER_DIRECTORY_DOWLOADING_KEYS',
  // Security
  COUNTER_SECURITY_ID_TOKEN_GENERATED = 'COUNTER_SECURITY_ID_TOKEN_GENERATED',
  COUNTER_SECURITY_ACCESS_TOKEN_GENERATED = 'COUNTER_SECURITY_ACCESS_TOKEN_GENERATED',
  LINE_SECURITY_AUTHORISE_REQUESTS = 'LINE_SECURITY_AUTHORISE_REQUESTS',
  LINE_SECURITY_ACCESS_TOKEN_REQUESTS = 'LINE_SECURITY_ACCESS_TOKEN_REQUESTS',
  LINE_SECURITY_ACCESS_TOKEN_RESPONSE_TIMES = 'LINE_SECURITY_ACCESS_TOKEN_RESPONSE_TIMES',
  LINE_SECURITY_AUTHORISE_RESPONSE_TIMES = 'LINE_SECURITY_AUTHORISE_RESPONSE_TIMES',
  TABLE_SECURITY_USAGE = 'TABLE_SECURITY_USAGE',
  // Account
  DOUGHNUT_ACCOUNTS_CONSENT_TYPE = 'DOUGHNUT_ACCOUNTS_CONSENT_TYPE',
  DOUGHNUT_ACCOUNTS_FLOW_COMPLETED = 'DOUGHNUT_ACCOUNTS_FLOW_COMPLETED',
  DOUGHNUT_ACCOUNTS_OB_VERSIONS = 'DOUGHNUT_ACCOUNTS_OB_VERSIONS',
  TABLE_ACCOUNTS_USAGE = 'TABLE_ACCOUNTS_USAGE',
  // Payments
  DOUGHNUT_PAYMENTS_CONSENT_TYPE = 'DOUGHNUT_PAYMENTS_CONSENT_TYPE',
  DOUGHNUT_PAYMENTS_SINGLE_CONSENTS_ACTIVITIES = 'DOUGHNUT_PAYMENTS_SINGLE_CONSENTS_ACTIVITIES',
  DOUGHNUT_PAYMENTS_DOMESTIC_CONSENTS_ACTIVITIES = 'DOUGHNUT_PAYMENTS_DOMESTIC_CONSENTS_ACTIVITIES',
  DOUGHNUT_PAYMENTS_DOMESTIC_SCHEDULED_CONSENTS_ACTIVITIES = 'DOUGHNUT_PAYMENTS_DOMESTIC_SCHEDULED_CONSENTS_ACTIVITIES',
  DOUGHNUT_PAYMENTS_DOMESTIC_STANDING_ORDERS_CONSENTS_ACTIVITIES = 'DOUGHNUT_PAYMENTS_DOMESTIC_STANDING_ORDERS_CONSENTS_ACTIVITIES',
  DOUGHNUT_PAYMENTS_INTERNATIONAL_CONSENTS_ACTIVITIES = 'DOUGHNUT_PAYMENTS_INTERNATIONAL_CONSENTS_ACTIVITIES',
  DOUGHNUT_PAYMENTS_INTERNATIONAL_SCHEDULED_CONSENTS_ACTIVITIES = 'DOUGHNUT_PAYMENTS_INTERNATIONAL_SCHEDULED_CONSENTS_ACTIVITIES',
  DOUGHNUT_PAYMENTS_INTERNATIONAL_STANDING_ORDER_CONSENTS_ACTIVITIES = 'DOUGHNUT_PAYMENTS_INTERNATIONAL_STANDING_ORDER_CONSENTS_ACTIVITIES',
  DOUGHNUT_PAYMENTS_FILE_CONSENTS_ACTIVITIES = 'DOUGHNUT_PAYMENTS_FILE_CONSENTS_ACTIVITIES',
  DOUGHNUT_PAYMENTS_COF = 'DOUGHNUT_PAYMENTS_COF',
  DOUGHNUT_PAYMENTS_OB_VERSIONS = 'DOUGHNUT_PAYMENTS_OB_VERSIONS',
  TABLE_PAYMENTS_USAGE = 'TABLE_PAYMENTS_USAGE',
  // FundsConfirmation
  DOUGHNUT_CONFIRMATION_OF_FUNDS_CONSENT_TYPE = 'DOUGHNUT_CONFIRMATION_OF_FUNDS_CONSENT_TYPE',
  DOUGHNUT_CONFIRMATION_OF_FUNDS_FLOW_COMPLETED = 'DOUGHNUT_CONFIRMATION_OF_FUNDS_FLOW_COMPLETED',
  DOUGHNUT_CONFIRMATION_OF_FUNDS_OB_VERSIONS = 'DOUGHNUT_CONFIRMATION_OF_FUNDS_OB_VERSIONS',
  TABLE_CONFIRMATION_OF_FUNDS_USAGE = 'TABLE_CONFIRMATION_OF_FUNDS_USAGE',
  // Events notifications
  DOUGHNUT_EVENTS_NOTIF_CALLBACK_SENT = 'DOUGHNUT_EVENTS_NOTIF_CALLBACK_SENT',
  COUNTER_EVENTS_NOTIF_FLOW_COMPLETED = 'COUNTER_EVENTS_NOTIF_FLOW_COMPLETED',
  DOUGHNUT_EVENTS_NOTIF_OB_VERSIONS = 'DOUGHNUT_EVENTS_NOTIF_OB_VERSIONS',
  TABLE_EVENTS_NOTIF_USAGE = 'TABLE_EVENTS_NOTIF_USAGE',
  // GSU
  COUNTER_GSU_PSUS = 'COUNTER_GSU_PSUS',
  COUNTER_GSU_TPPS = 'COUNTER_GSU_TPPS',
  DOUGHNUT_GSU_OBRI_SESSIONS = 'DOUGHNUT_GSU_OBRI_SESSIONS',
  DOUGHNUT_GSU_CALL_BY_STATUS = 'DOUGHNUT_GSU_CALL_BY_STATUS',
  DOUGHNUT_GSU_OB_VERSIONS = 'DOUGHNUT_GSU_OB_VERSIONS',
  DOUGHNUT_GSU_OB_API_TYPE = 'DOUGHNUT_GSU_OB_API_TYPE',
  LINE_GSU_API_CALLS = 'LINE_GSU_API_CALLS',
  LINE_GSU_API_CALLS_PER_WEEK = 'LINE_GSU_API_CALLS_PER_WEEK',
  LINE_GSU_API_RESPONSE_TIME = 'LINE_GSU_API_RESPONSE_TIME',
  // Settings
  TABLE_SETTINGS_ENDPOINT_USAGE_RAW = 'TABLE_SETTINGS_ENDPOINT_USAGE_RAW'
}

export interface IPdfWidgetAttributes {
  [key: string]: string | number;
}

export interface IPdfWidget {
  type: IPdfWidgetType;
  info: boolean;
  width: 25 | 33 | 50 | 66 | 75 | 100;
  attributes?: IPdfWidgetAttributes;
}

export enum IPdfPageOrientation {
  LANDSCAPE = 'LANDSCAPE',
  PORTRAIT = 'PORTRAIT'
}

export enum IPdfPageType {
  COVER = 'COVER',
  PAGE = 'PAGE'
}

export interface IPdfPage {
  from?: string;
  to?: string;
  type: IPdfPageType.PAGE;
  orientation: IPdfPageOrientation;
  widgets: IPdfWidget[];
}

export interface IPdfCover {
  from?: string;
  to?: string;
  title: string;
  type: IPdfPageType.COVER;
  orientation: IPdfPageOrientation.PORTRAIT;
}

export interface IPdfReportConfig {
  v: number; // version
  from?: string;
  to?: string;
  period?: IDatesPeriod;
  pages: (IPdfCover | IPdfPage)[];
}
