FROM timbru31/java-node

WORKDIR /src
ADD ./projects/analytics/server /src

RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
    && apt-get update \
    && apt-get install -y google-chrome-unstable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst fonts-freefont-ttf \
      --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*
RUN npm ci
ENV PORT 80
RUN npm run build

EXPOSE 80

ENV DOMAIN ""
ENV APP_URL "https://analytics.DOMAIN"
ENV NODE_ENV "production"

COPY projects/analytics/docker/start-server.sh /opt/start-server.sh
COPY projects/analytics/docker/deployment-settings.js /src/dist/deployment-settings.js

CMD ["/opt/start-server.sh"]
