version: '1.0'

stages:
  - prepare
  - build
  - unit-test
  - docker-ui
  - docker-push
  - trigger-deploy

steps:
  main_clone:
    type: git-clone
    title: Git Clone OB UI
    repo: ForgeRock/ob-analytics
    revision: '${{CF_REVISION}}'
    git: github-bot

  #  Prepare stage
  set-global-variables:
    image: jess/jq
    stage: 'prepare'
    title: 'Set up global variables'
    working-directory: ${{main_clone}}/forgerock-openbanking-ui
    commands:
      - 'export PROJECT_VERSION=$(jq -r ".project_version" package.json)'
      - 'cf_export PROJECT_VERSION'
      - cf_export BUILD_VERSION=${PROJECT_VERSION}-${CF_SHORT_REVISION}

  # Build stage
  install-npm-dependencies:
    type: build
    stage: 'build'
    title: 'Build UI docker image, used for docker caching'
    image_name: obri/build-analytics-ui
    working-directory: ${{main_clone}}/forgerock-openbanking-ui
    tag: 'latest'
    build_arguments:
      - OB_UI_LIBS_SSH_KEY=${{GITHUB_OB_UI_LIBS_SSH_KEY}}
      - GITHUB_ACCESS_TOKEN=${{GITHUB_ACCESS_TOKEN}}
  push-npm-dependencies-image:
    type: push
    stage: 'build'
    title: 'Push npm-dependencies-image to bintray'
    candidate: ${{install-npm-dependencies}}

  test-stage:
    type: parallel
    stage: 'unit-test'
    steps:
      # Unit-test stage
      ui-unit-test:
        image: ${{install-npm-dependencies}}
        title: 'Run UI unit tests'
        working-directory: /src/
        commands:
          - npm run test.ci

      ui-linter:
        image: ${{install-npm-dependencies}}
        title: 'Run UI linter'
        working-directory: /src/
        commands:
          - ./node_modules/@angular/cli/bin/ng lint

  docker-ui-one-build:
    type: parallel
    stage: 'docker-ui'
    steps:
      build-analytics-ui-docker-image:
        type: build
        stage: 'docker-ui'
        title: 'Build analytics ui docker image'
        image_name: obri/analytics-ui
        working-directory: ${{main_clone}}/forgerock-openbanking-ui
        build_arguments:
          - BUILD_VERSION=${{BUILD_VERSION}}
        dockerfile: projects/analytics/docker/Dockerfile
        tag: ${{CF_REVISION}}
      build-analytics-node-docker-image:
        type: build
        stage: 'docker-ui'
        title: 'Build analytics node server docker image'
        image_name: obri/analytics-node
        working-directory: ${{main_clone}}/forgerock-openbanking-ui
        build_arguments:
          - BUILD_VERSION=${{BUILD_VERSION}}
        dockerfile: projects/analytics/docker/Dockerfile-server
        tag: ${{CF_REVISION}}

  # Docker-push stage
  docker-push:
    type: parallel
    stage: 'docker-push'
    steps:
      push-analytics-docker-image:
        type: push
        title: 'Push analytics ui docker image to bintray'
        candidate: ${{build-analytics-ui-docker-image}}
        tags:
          - ${{BUILD_VERSION}}
      push-analytics-node-docker-image:
        type: push
        title: 'Push analytics node docker image to bintray'
        candidate: ${{build-analytics-node-docker-image}}
        tags:
          - ${{BUILD_VERSION}}

  clone-ob-deploy:
    type: git-clone
    stage: 'trigger-deploy'
    title: 'Clone ob-deploy repo'
    git: github-bot
    repo: forgeCloud/ob-deploy
    when:
      branch:
        only:
          - master
  update-release-json:
    image: codefreshio/git-image:latest
    stage: 'trigger-deploy'
    title: 'Update release.json'
    description: 'Update release.json file'
    working_directory: ${{clone-ob-deploy}}
    commands:
      - apt update && apt install jq
      - jq -M  '[ .[] | if (.service  | contains("analytics-")) then .version |= "${{BUILD_VERSION}}" else . end ]' client_releases/master-dev/releases.json > client_releases/master-dev/releases.json.tmp
      - mv client_releases/master-dev/releases.json.tmp client_releases/master-dev/releases.json
      - git config --global user.email "codefresh@codefresh.io"
      - git config --global user.name "Codefresh"
      - git add client_releases/master-dev/releases.json
      - git commit --allow-empty -m "Bumping UI version ${{BUILD_VERSION}}"
      - git push https://${{GITHUB_USERNAME}}:${{GITHUB_ACCESS_TOKEN}}@github.com/ForgeCloud/ob-deploy.git "master"
    when:
      branch:
        only:
          - master
  trigger-ob-deploy-master:
    title: 'Trigger deploy pipeline'
    stage: 'trigger-deploy'
    image: codefresh/cli
    commands:
      - codefresh run ForgeCloud/ob-deploy/ob-deploy-master-dev --branch ${{CF_BRANCH}} --detach -t "default"
    when:
      branch:
        only:
          - master
