version: '3.7'
services:
  analytics-ui:
    image: eu.gcr.io/openbanking-214714/obri/analytics-ui:latest
    ports:
      - "4206:443"
    environment:
      DOMAIN: dev-ob.forgerock.financial
      #TEMPLATE: hsbc
      # The following env vars are all based on DOMAIN but can be set with any value (interesting locally with different ports)
      NODE_BACKEND_URL: "https://analytics.DOMAIN:5000" # "https://node.analytics.DOMAIN"
      METRICS_BACKEND_URL: "https://service.metrics.DOMAIN:8074"
    volumes:
      - ./ssl/analytics.forgerock.financial.key:/etc/nginx/certs/analytics.forgerock.financial.key
      - ./ssl/analytics.forgerock.financial.crt:/etc/nginx/certs/analytics.forgerock.financial.crt
      - ./ssl/analytics.forgerock.financial.conf:/etc/nginx/conf.d/default.conf
  analytics-node:
    image: eu.gcr.io/openbanking-214714/obri/analytics-node:latest
    ports:
      - "5000:8443"
    environment:
      DOMAIN: dev-ob.forgerock.financial
      NODE_ENV: "compose"
      PORT: 8443
      # The following env vars are all based on DOMAIN but can be set with any value (interesting locally with different ports)
      APP_URL: "https://analytics-ui:443"
      CORS_ORIGIN: "https://analytics.DOMAIN:4206"
    volumes:
      - ./ssl/analytics.forgerock.financial.key:/src/dist/server.key
      - ./ssl/analytics.forgerock.financial.crt:/src/dist/server.crt


