version: '3.7'
services:
  analytics-ui:
    image: r.cfcr.io/openbanking/obri/analytics-ui:latest
    ports:
      - "4206:443"
    environment:
      DOMAIN: ui-integ.forgerock.financial
      TEMPLATE: hsbc
      # The following env vars are all based on DOMAIN but can be set with any value (interesting locally with different ports)
      NODE_BACKEND_URL: "https://dev.analytics.ui-integ.forgerock.financial:5000" # "https://node.analytics.DOMAIN"
      # METRICS_BACKEND_URL: "https://service.metrics.DOMAIN"
    volumes:
      - ./ssl/k-all.ui-integ.forgerock.financial.key:/etc/nginx/certs/ui-integ.forgerock.financial.key
      - ./ssl/all.ui-integ.forgerock.financial.crt:/etc/nginx/certs/ui-integ.forgerock.financial.crt
      - ./ssl/ui-integ.forgerock.financial.conf:/etc/nginx/conf.d/default.conf
  analytics-node:
    image: r.cfcr.io/openbanking/obri/analytics-node:latest
    ports:
      - "5000:8443"
    environment:
      DOMAIN: ui-integ.forgerock.financial
      NODE_ENV: "compose"
      PORT: 8443
      # The following env vars are all based on DOMAIN but can be set with any value (interesting locally with different ports)
      APP_URL: "https://analytics-ui:443"
      CORS_ORIGIN: "https://dev.analytics.ui-integ.forgerock.financial:4206"
    volumes:
      - ./ssl/k-all.ui-integ.forgerock.financial.key:/src/dist/server.key
      - ./ssl/all.ui-integ.forgerock.financial.crt:/src/dist/server.crt


     