export enum IDatesPeriod {
  TODAY = 'TODAY',
  YESTERDAY = 'YESTERDAY',
  LAST_3_DAYS = 'LAST_3_DAYS',
  CURRENT_WEEK = 'CURRENT_WEEK',
  LAST_WEEK = 'LAST_WEEK',
  LAST_3_WEEKS = 'LAST_3_WEEKS',
  LAST_6_WEEKS = 'LAST_6_WEEKS',
  LAST_MONTH = 'LAST_MONTH',
  LAST_3_MONTHS = 'LAST_3_MONTHS',
  LAST_6_MONTHS = 'LAST_6_MONTHS',
  CURRENT_QUARTER = 'CURRENT_QUARTER',
  QUARTER_MINUS_1 = 'QUARTER_MINUS_1',
  QUARTER_MINUS_2 = 'QUARTER_MINUS_2',
  QUARTER_MINUS_3 = 'QUARTER_MINUS_3',
  CURRENT_YEAR = 'CURRENT_YEAR',
  LAST_YEAR = 'LAST_YEAR'
}
