name: pull-request

on: [pull_request]
    
jobs:
  build:
    runs-on: ubuntu-latest
    name: Check PR Itegrity
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v2
      with:
        java-version: "11"
        distribution: 'zulu'
        cache: 'maven'
        architecture: x64

    - name: Docker login
      run: echo "${{ secrets.GCR_JSON_KEY_BASE64 }}" | base64 -d | docker login eu.gcr.io -u _json_key --password-stdin

    - name: Check Copyright
      run: mvn license:check

    - name: Build and Test
      run: |
        sudo bash -c 'echo "127.0.0.1   metrics-services" >> /etc/hosts'
        mvn -B clean verify # this command executes each default lifecycle phase in order (validate, compile, test, package, etc), before executing verify.

    - uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_ACCESS_TOKEN }}
