name: Build-UI

on:
  # Trigger the workflow on push
  # Only for the master branch
  push:
    branches:
      - master
    paths:
      - ".github/workflows/ui.yml"
      - "forgerock-openbanking-ui/**"

env:
  GITHUB_ACCESS_TOKEN: ${{ secrets.FORGECLOUD_ACCESS_TOKEN }}
  GITHUB_SHA: ${{ github.sha }}

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Run tests
        working-directory: ./forgerock-openbanking-ui
        run: |
          npm ci
          npm run test.ci
          ./node_modules/@angular/cli/bin/ng lint
      - name: Prepare customers
        working-directory: ./forgerock-openbanking-ui
        run: git clone https://$GITHUB_ACCESS_TOKEN@github.com/ForgeCloud/ob-customers.git customers
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: customers
          path: forgerock-openbanking-ui/customers
  build_analytics_ui:
    name: Build Analytics App
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: customers
          path: forgerock-openbanking-ui/customers
      - working-directory: ./forgerock-openbanking-ui
        run: cp -R ./customers/* themes/
      - name: Build Analytics UI docker image
        working-directory: ./forgerock-openbanking-ui
        run: |
          export REGISTRY=eu.gcr.io/openbanking-214714/obri/analytics-ui
          export BUILD_VERSION=$(jq -r ".project_version" package.json)-${GITHUB_SHA::7}
          export PROJECT_VERSION_JSON=$(jq -r ".project_version" package.json)
          export PROJECT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "Building docker image ${REGISTRY}:${BUILD_VERSION}"
          echo "${{ secrets.GCR_JSON_KEY_BASE64 }}" | base64 -d | docker login eu.gcr.io -u _json_key --password-stdin
          docker build --build-arg BUILD_VERSION=$BUILD_VERSION -f projects/analytics/docker/Dockerfile \
          -t $REGISTRY:latest -t $REGISTRY:$BUILD_VERSION -t $REGISTRY:$PROJECT_VERSION_JSON -t $REGISTRY:$PROJECT_VERSION .
          docker push $REGISTRY:latest
          docker push $REGISTRY:$BUILD_VERSION
          docker push $REGISTRY:$PROJECT_VERSION
          docker push $REGISTRY:$PROJECT_VERSION_JSON
  build_analytics_backend:
    name: Build Analytics Backend
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: customers
          path: forgerock-openbanking-ui/customers
      - working-directory: ./forgerock-openbanking-ui
        run: cp -R ./customers/* themes/
      - name: Build analytics backend docker image
        working-directory: ./forgerock-openbanking-ui
        run: |
          export REGISTRY=eu.gcr.io/openbanking-214714/obri/analytics-node
          export BUILD_VERSION=$(jq -r ".project_version" package.json)-${GITHUB_SHA::7}
          export PROJECT_VERSION_JSON=$(jq -r ".project_version" package.json)
          export PROJECT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "Building docker image ${REGISTRY}:${BUILD_VERSION}"
          echo "${{ secrets.GCR_JSON_KEY_BASE64 }}" | base64 -d | docker login eu.gcr.io -u _json_key --password-stdin
          docker build --build-arg BUILD_VERSION=$BUILD_VERSION -f projects/analytics/docker/Dockerfile-server \
          -t $REGISTRY:latest -t $REGISTRY:$BUILD_VERSION -t $REGISTRY:$PROJECT_VERSION_JSON -t $REGISTRY:$PROJECT_VERSION .
          docker push $REGISTRY:latest
          docker push $REGISTRY:$BUILD_VERSION
          docker push $REGISTRY:$PROJECT_VERSION
          docker push $REGISTRY:$PROJECT_VERSION_JSON
  update_ob_deploy:
    name: Update ob-deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs: [build_analytics_ui, build_analytics_backend]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - working-directory: ./forgerock-openbanking-ui
        id: version
        run: |
          export BUILD_VERSION=$(jq -r ".project_version" package.json)-${GITHUB_SHA::7}
          echo "::set-output name=BUILD_VERSION::$BUILD_VERSION"
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          repository: "forgeCloud/ob-deploy"
          token: ${{ secrets.FORGECLOUD_ACCESS_TOKEN }}
          path: ob-deploy
      - name: Commit ob-deploy version update
        working-directory: ./ob-deploy
        run: |
          jq -M  '[ .[] | if (.service  | contains("analytics-")) then .version |= "${{ steps.version.outputs.BUILD_VERSION }}" else . end ]' client_releases/master-dev/releases.json > client_releases/master-dev/releases.json.tmp
          mv client_releases/master-dev/releases.json.tmp client_releases/master-dev/releases.json
          git config --global user.email "codefresh@codefresh.io"
          git config --global user.name "Codefresh"
          git add client_releases/master-dev/releases.json
          git commit --allow-empty -m "Bumping Analytics UI & Backend version ${{ steps.version.outputs.BUILD_VERSION }}"
      - name: Temporarily disable "include administrators" protection
        uses: benjefferies/branch-protection-bot@master
        if: always()
        with:
          access-token: ${{ secrets.FORGECLOUD_ACCESS_TOKEN }}
          enforce_admins: false
          owner: forgeCloud
          repo: ob-deploy
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.FORGECLOUD_ACCESS_TOKEN }}
          directory: ./ob-deploy
          repository: "forgeCloud/ob-deploy"
          branch: master
      - name: Enable "include administrators" branch protection
        uses: benjefferies/branch-protection-bot@master
        if: always()
        with:
          access-token: ${{ secrets.FORGECLOUD_ACCESS_TOKEN }}
          enforce_admins: true
          owner: forgeCloud
          repo: ob-deploy
